name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            unzip \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            build-essential \
            libstdc++6
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 Cython==0.29.33

      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v4
        with:
          api-level: 29
          ndk-version: 21.4.7075529

      - name: Build APK with Buildozer
        run: |
          echo y | buildozer android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatgpt_kivy.apk
          path: bin/*.apk
