name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.10

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            python3-setuptools python3-wheel python3-virtualenv \
            libtool libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev libc6-dev libncurses5-dev \
            libstdc++6 libjpeg-dev libfreetype6-dev \
            ccache autoconf automake cmake pkg-config

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install cython virtualenv
          pip install buildozer

      - name: Set environment variables
        run: |
          echo "PATH=$PATH:$HOME/.buildozer/android/platform/apache-ant-1.9.4/bin" >> $GITHUB_ENV
          echo "ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROIDAPI=33" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

      - name: Initialize and build with Buildozer
        run: |
          buildozer android update
          buildozer android clean
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: attendance-app-apk
          path: bin/*.apk
