name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            openjdk-17-jdk \
            unzip \
            zlib1g \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            build-essential \
            libstdc++6
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 Cython==0.29.33

      - name: Set JAVA_HOME to Java 17
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          ndk-version: 25.2.9519653

      - name: Build APK with Buildozer
        run: |
          echo y | buildozer android debug

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks

      - name: Sign APK with apksigner
        run: |
          APK_PATH=$(find bin/ -name "*.apk" | head -n 1)
          echo "Signing $APK_PATH"
          $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign \
            --ks my-release-key.jks \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out signed-app.apk \
            "$APK_PATH"

      - name: Verify signed APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify signed-app.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: chatgpt_kivy_signed.apk
          path: signed-app.apk
